### ISSUE TITLE
make4FGLxml.py not working for DR4

### ISSUE THREAD

**Issue by emolinlu** [physicsranger/make4FGLxml#63]
Thanks for the nice update. However, the make4FGLxml.py script is not working for DR4, since the _-DR 4_ option is not included in the possible choices.

**Comment by physicsranger** [comment]
Whoops, that's an embarrassing goof on my part.  Good catch, thank you.  I thought I had checked everything but clearly I missed this somehow (I really need to develop a more formalized/thorough set of tests).
This is now fixed in the latest release, v1.10.9, installable via:
```pip install LATSourceModel --upgrade```
I tested this by upgrading on a different machine and running the script successfully.
