### ISSUE TITLE
CygnusLoop_GALEX.fits

### ISSUE THREAD

**Issue by devbhakt** [physicsranger/make4FGLxml#67]
Hello,

I did a fresh install in a new conda environment following the install instructions for Fermitools and LATSourceModel. I tried generating photon weights using gtdiffrsp and gtsrcprob and received a warning when I use make4FGLxml saying Extended source Cygnus Loop in model, make sure that the following path to extended template is correct: $(FERMI_DIR)/data/pyBurstAnalysisGUI/templates/CygnusLoop_GALEX.fits

gtdiffrsp and gtsrcprob both fail because the template file does not exist. There is a CygnusLoop.fits template file in there so I am not sure if this is searching for a mislabeled file within the code. Would a temporary fix be to make a copy of the CygnusLoop.fits file and relabel it CygnusLoop_GALEX.fits?

I have searched for the template file in all of the Fermi repositories on github but have not found one anywhere.

**Comment by physicsranger** [comment]
Thanks for checking out the package and reaching out.

I touched base with the folks at the Fermi Science Support Center (very helpful people to know, fermihelp@milkyway.gsfc.nasa.gov) since these files are not something LATSourceModel is responsible for (it just finds the expected file name from either the FITS or XML version of the catalog).  Quoting from Nestor:

"...download the latest version of the extended source template file from 
https://fermi.gsfc.nasa.gov/ssc/data/access/lat/14yr_catalog/LAT_extended_sources_14years.tgz

After expanding it with tar xvf LAT_extended_sources_14years.tgz
there should be a directory named Templates/. The file should be in there he has to copy it into 
$(FERMI_DIR)/data/pyBurstAnalysisGUI/templates/."

He adds that it would be a good idea to copy all of the file from the unpacked Templates directory into the FERMI_DIR direction.

Let me know if that does it for you and we can close this issue.

--Tyrel

**Comment by devbhakt** [comment]
Yup. That worked! You can close the issue

**Comment by physicsranger** [comment]
Awesome, glad to hear it!
