### ISSUE TITLE
TS issue

### ISSUE THREAD

**Issue by Hend30** [physicsranger/make4FGLxml#68]
I get these error messages when I run make4FGLxml
 **"File "/opt/anaconda/envs/fermi/bin/make4FGLxml", line 8, in <module>
    sys.exit(cli())
  File "/opt/anaconda/envs/fermi/lib/python3.9/site-packages/LATSourceModel/make4FGLxml.py", line 160, in cli
    source_list.make_model(args.galactic_file,args.galactic_name,
  File "/opt/anaconda/envs/fermi/lib/python3.9/site-packages/LATSourceModel/SourceList.py", line 305, in make_model
    self.create_XML_model()
  File "/opt/anaconda/envs/fermi/lib/python3.9/site-packages/LATSourceModel/SourceList.py", line 336, in create_XML_model
    self.get_sources_xml()
  File "/opt/anaconda/envs/fermi/lib/python3.9/site-packages/LATSourceModel/SourceList.py", line 595, in get_sources_xml
    ('significant',float(source.getAttribute('TS_value'))>=self.sigma_to_free)])
ValueError: could not convert string to float: ''
"**

**Comment by Hend30** [comment]
Sorted!
It was a 4FGL catalog problem.

**Comment by sfegan** [comment]
We have had the same problem a few times at LLR when analyzing ROIs that contain the Crab Nebula. I understood it to be due to the fact that the Crab is modelled by multiple components, one of which is fixed in the catalog, so there is no TS_value given for it and the code dies. The same problem could also occur for sources that don't have "Variability_Index".

We ended up fixing it by changing the code to test explicitly that these two attributes aren't a null string before trying to make them into float :

            #evaluate variability and significance threshold info
            self.sources[name].update([('variable',source.getAttribute('Variability_Index')=="" or float(source.getAttribute('Variability_Index'))>=self.variability_threshold),
                ('significant',source.getAttribute('TS_value')=="" or float(source.getAttribute('TS_value'))>=self.sigma_to_free)])

We default to keeping them in the model if the attribute isn't present.

**Comment by physicsranger** [comment]
I'm glad you were able to figure out a fix on your own Hend30, but your issue did make me think that the code needs some more robust value and error checking.  Thanks for the deeper trouble shooting sfegan (and raising the other issue).

**Comment by Hend30** [comment]
@sfegan I tried to fix it that way but got other errors :(
@physicsranger That issue was solved by replacing gll_psc_v32.xml with the fits version gll_psc_v34.fits.
